#### Utilit√°rios

#### Pr√© processamento

In [8]:
import pandas as pd
import os

# Configurar Pandas para exibir n√∫meros inteiros completos
pd.options.display.float_format = '{:.00f}'.format
try:
    df_area = pd.read_csv("IBGE_area_geografica_98-22.csv", encoding="utf-8", sep=";", skiprows=1)
    print(f"  ‚úî IBGE_area_geografica_98-22.csv carregado como df_area \n")
    print(df_area.dtypes)
except Exception as e:
        print(f"Erro ao ler arquivo : {e}")


#filtrando estados de interesse
estados = ["Acre", "Amazonas", "Amap√°", "Maranh√£o", "Par√°", "Roraima", "Tocantins", "Rond√¥nia", "Mato Grosso"]
df_area = df_area.query("@estados in Estado")

print(f"\n  üåé Filtrados apenas os estados desejados em df_area")

#removendo colunas indesejadas
col_para_remover = [col for col in ["Codigo", "C√≥digo", "Sigla"] if col in df_area.columns]
df_area = df_area.drop(columns = col_para_remover)

print(f"  üóëÔ∏è Colunas removidas de df_area: {col_para_remover}")

#convertendo valores str para int
df_area.iloc[:, 1:] = df_area.iloc[:, 1:].replace(",", ".", regex=True)  # Troca v√≠rgula por ponto
for col in df_area.iloc[:, 1:].columns:
    df_area[f"{col}"] = pd.to_numeric(df_area[f"{col}"], errors='coerce')

print(f"  üîÑ Colunas 1998 a 2022 convertidas para tipo inteiro")

  ‚úî IBGE_area_geografica_98-22.csv carregado como df_area

Sigla     object
C√≥digo     int64
Estado    object
1998      object
2000      object
2010      object
2013      object
2014      object
2015      object
2016      object
2017      object
2018      object
2019      object
2020      object
2021      object
2022      object
dtype: object

  üåé Filtrados apenas os estados desejados em df_area
  üóëÔ∏è Colunas removidas de df_area: ['C√≥digo', 'Sigla']
  üîÑ Colunas 1998 a 2022 convertidas para tipo inteiro

#### Calculando M√©dia

In [6]:
df_area["M√©dia Territorial"] = df_area.iloc[:, 1:].mean(axis=1)

In [7]:
df_area

,Estado,1998,2000,2010,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,M√©dia Territorial
0,Acre,153150,152522,164123,164124,164124,164124,164124,164124,164124,164124,164173,164173,164173,162399
2,Amazonas,1577820,1570947,1559159,1559149,1559149,1559149,1559147,1559147,1559168,1559168,1559168,1559168,1559256,1561507
3,Amap√°,143454,142816,142829,142829,142829,142829,142829,142829,142471,142471,142471,142471,142471,142738
9,Maranh√£o,333366,331919,331937,331937,331937,331937,331937,331937,329642,329642,329651,329651,329651,331165
12,Mato Grosso,906807,903385,903366,903378,903378,903198,903202,903202,903207,903207,903207,903207,903208,903535
13,Par√°,1253164,1247703,1247955,1242966,1242966,1242967,1242967,1242967,1240771,1240883,1240882,1240882,1240882,1243689
20,Rond√¥nia,238513,237565,237591,237591,237591,237765,237765,237765,237765,237765,237765,237765,237754,237766
21,Roraima,225116,224118,224301,224303,224303,224301,224301,224301,224274,223645,223645,223645,223645,224146
26,Tocantins,278421,277297,277721,277721,277721,277721,277720,277720,277720,277467,277424,277424,277424,277654

In [ ]:
df_area.to_csv("media_territorial", index = False, encoding="utf-8")
path = os.getcwd()

print("üìÇ Dataframe salvo em: ", path)